[tool.poetry]
name = "your-project-name"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.10"
# other dependencies here

[tool.poetry.dev-dependencies]
# dev dependencies here
